# Generated by Django 3.2.8 on 2021-10-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211014_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expiration_date',
            field=models.DateTimeField(null=True, verbose_name=' تاريخ انتهاء الجواز'),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport_number',
            field=models.CharField(max_length=10, null=True, verbose_name='رقم الجواز'),
        ),
    ]
