# Generated by Django 3.2.8 on 2021-10-14 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211014_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expiration_date',
            field=models.DateField(null=True, verbose_name=' تاريخ انتهاء الجواز'),
        ),
    ]
