# Generated by Django 3.2.8 on 2021-10-14 15:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم النشاط')),
            ],
            options={
                'verbose_name': 'النشاط',
                'verbose_name_plural': 'النشاط',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الموقع')),
            ],
            options={
                'verbose_name': 'الموقع',
                'verbose_name_plural': 'الموقع',
            },
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('Jan', 'يناير'), ('Feb', 'فبراير'), ('Mar', 'مارس'), ('Apr', 'أبريل'), ('May', 'مايو'), ('Jun', 'يونيو'), ('Jul', 'يوليو'), ('Aug', 'أغسطس'), ('Sep', 'سبتمبر'), ('Oct', 'أكتوبر'), ('Nov', 'نوفمبر'), ('Dec', 'ديسمبر')], max_length=150, verbose_name='الشهر')),
                ('year', models.CharField(choices=[(2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026)], max_length=150, validators=[django.core.validators.RegexValidator('^20[0-9]{2}$', 'سنة خاطئة')], verbose_name='السنة')),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='affairs.activity', verbose_name='اسم النشاط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'الشهر',
                'verbose_name_plural': 'الشهر',
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(verbose_name='رقم اليوم')),
                ('attendance', models.BooleanField(default=True, verbose_name='الحضور')),
                ('extra_work_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='عدد سعات عمل اضافية')),
                ('deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='الخصم')),
                ('rewards', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='المكافئات')),
                ('loans', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='السلف')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='affairs.location', verbose_name='الموقع')),
                ('month', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='affairs.month', verbose_name='الشهر')),
            ],
            options={
                'verbose_name': 'اليوم',
                'verbose_name_plural': 'اليوم',
            },
        ),
    ]
