# Generated by Django 3.2.8 on 2021-10-15 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('affairs', '0002_auto_20211015_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='month',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='months', to='affairs.month', verbose_name='الشهر'),
        ),
        migrations.AlterField(
            model_name='month',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_months', to=settings.AUTH_USER_MODEL, verbose_name='العميل'),
        ),
    ]
